### ISSUE TITLE
Microsoft Authentication Library

### ISSUE THREAD

**Issue by kmukku** [stuartpreston/nuxt-auth-azuread-example#16]
While going thru this set up, I got a notification on Azure that "Applications will need to be upgraded to Microsoft Authentication Library". What are your thoughts on this? Is this still valid way to implement Azure AD authentication on Nuxt or should I find another way?

**Comment by stuartpreston** [comment]
Sorry I didn't see this until I was updating dependencies for this project. Good question. The approach I took just uses generic PKCE auth so I believe it's not required to use MSAL at all.
